-keep interface io.proteus.core.domain.FeatureContext { *; }
-keep interface io.proteus.core.provider.FeatureConfigProvider { *; }
-keep interface io.proteus.core.provider.FeatureConfigProviderFactory { *; }
